import { serve } from "std/http/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { pdfText } = await req.json();

    if (!pdfText) {
      throw new Error("Missing PDF text");
    }

    const genAI = new GoogleGenerativeAI(Deno.env.get("GEMINI_API_KEY")!);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `
      Eres un experto en Personal Branding y LinkedIn Coach con más de 10 años de experiencia ayudando a CEOs y emprendedores a escalar su presencia digital.
      Tu tarea es realizar una AUDITORÍA MAESTRA de este perfil de LinkedIn basándote en el texto extraído del PDF.

      [REGLAS CRÍTICAS]
      1. SÉ CRÍTICO pero CONSTRUCTIVO. El usuario quiere mejorar, no que le digan que todo está bien.
      2. USA MÉTRICAS Y FÓRMULAS: Evalúa si usan fórmulas en el titular o métricas en la experiencia.
      3. RESPONDE SIEMPRE EN ESPAÑOL.
      4. RESPONDE ESTRICTAMENTE EN FORMATO JSON. No incluyas texto fuera del JSON.
      5. ELIMINA CARACTERES ESPECIALES: El JSON final debe ser limpio y fácil de parsear.

      [ESTRUCTURA DEL JSON REQUERIDA]
      {
        "perfil_resumen": {
          "nombre": "string",
          "sector": "string",
          "score_actual": "number (0-100)"
        },
        "pilares": {
          "pilar_1_fundamento": {
            "score": "number",
            "analisis_titular": "Resumen crítico del titular actual",
            "propuesta_titular_a": "Opción SEO (Rol | Valor | Palabra Clave)",
            "propuesta_titular_b": "Opción Autoridad (Ayudo a X a conseguir Y mediante Z)",
            "foto_banner_check": "Feedback sobre lo que se deduce de su imagen actual",
            "url_check": "Feedback sobre su URL de LinkedIn"
          },
          "pilar_2_narrativa": {
            "score": "number",
            "gancho_analisis": "Cómo son las primeras 2 líneas de su 'Acerca de'",
            "redaccion_gancho_sugerida": "Reescritura de alto impacto (máximo 3 líneas)",
            "experiencia_analisis": "Análisis de si usa logros cuantificables",
            "experiencia_mejoras": [
              {
                "empresa": "string",
                "propuesta_metrica": "Sugerencia de logro cuantificable para esta posición"
              }
            ]
          },
          "pilar_3_visibilidad": {
            "score": "number",
            "estrategia_contenido": "3 tipos de posts que debería estar publicando",
            "estrategia_networking": "Consejo sobre cómo interactuar con otros líderes"
          }
        },
        "quick_wins": ["Victoria 1", "Victoria 2", "Victoria 3"]
      }

      [TEXTO DEL PDF]
      ${pdfText}
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    let text = response.text();

    // Limpiar posibles bloques de código Markdown
    text = text.replace(/```json/g, "").replace(/```/g, "").trim();

    // Validar JSON
    try {
      JSON.parse(text);
    } catch (e) {
      console.error("Invalid JSON generated by AI:", text);
      throw new Error("La IA generó una respuesta inválida. Reintenta.");
    }

    return new Response(text, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/json",
      },
    });
  } catch (error: any) {
    console.error("Error in analyze-profile:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
