import React from 'react';
import { AppLanguage } from '../../../types';
import { Sparkles, XCircle, CheckCircle2 } from 'lucide-react';
import { translations } from '../../../translations';

interface VoiceExamplesProps {
    language: AppLanguage;
    styleName: string;
    description: string;
}

const VoiceExamples: React.FC<VoiceExamplesProps> = ({ language, styleName }) => {
    // Determine generic vs specific based on styleName (simulation)
    // In a real app, this would be generated by AI, but for now we use static "Before/After" logic 
    // tailored loosely to the style name + some hardcoded examples for demo effect.

    const isSpanish = language === 'es';

    const GENERIC_EXAMPLE = isSpanish
        ? "Estoy emocionado de anunciar que lanzamos nuestro nuevo producto. Ha sido mucho trabajo pero valió la pena. ¡Comprenlo ya!"
        : "I am excited to announce we launched our new product today. It was hard work but worth it. Buy it now!";

    const TRANSFORMED_EXAMPLE = isSpanish
        ? "Llevamos 6 meses en silencio.\n\nConstruyendo. Rompiendo. Reconstruyendo.\n\nHoy, por fin ve la luz.\n\nNo es solo un 'producto'. Es la solución que yo mismo necesitaba hace 2 años.\n\n¿El resultado? 👇"
        : "We went silent for 6 months.\n\nBuilding. Breaking. Rebuilding.\n\nToday, it finally sees the light.\n\nIt's not just a 'product'. It's the solution I desperately needed 2 years ago.\n\nThe result? 👇";

    return (
        <div className="bg-slate-50 rounded-xl p-5 border border-slate-200/60/60 mt-6 animate-in fade-in slide-in-from-bottom-2">
            <h4 className="font-bold text-slate-900 mb-4 flex items-center gap-2 text-sm uppercase tracking-wide">
                <Sparkles className="w-4 h-4 text-brand-500" />
                {isSpanish ? 'Impacto de tu Voz' : 'Voice Impact Preview'}
            </h4>

            <div className="grid md:grid-cols-2 gap-4">
                {/* Before */}
                <div className="bg-white p-4 rounded-lg border border-red-100 relative group">
                    <div className="absolute -top-2.5 left-3 px-2 py-0.5 bg-red-100 text-red-700 text-[10px] font-bold uppercase rounded-full border border-red-200 flex items-center gap-1">
                        <XCircle className="w-3 h-3" />
                        {isSpanish ? 'Genérico (Sin Ti)' : 'Generic (Without You)'}
                    </div>
                    <p className="text-slate-500 text-sm leading-relaxed mt-2 line-through decoration-red-200 decoration-2">
                        {GENERIC_EXAMPLE}
                    </p>
                </div>

                {/* After */}
                <div className="bg-white p-4 rounded-lg border border-brand-200 relative ring-1 ring-brand-100">
                    <div className="absolute -top-2.5 left-3 px-2 py-0.5 bg-brand-100 text-brand-700 text-[10px] font-bold uppercase rounded-full border border-brand-200 flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" />
                        {styleName || (isSpanish ? 'Tu Nueva Voz' : 'Your New Voice')}
                    </div>
                    <p className="text-slate-800 text-sm leading-relaxed mt-2 font-medium whitespace-pre-wrap">
                        {TRANSFORMED_EXAMPLE}
                    </p>
                </div>
            </div>

            <p className="text-xs text-center text-slate-400 mt-4 italic">
                {isSpanish
                    ? '*Ejemplo demostrativo. Tu voz real se aplicará a todos tus futuros posts.'
                    : '*Demo example. Your actual voice will apply to all future posts.'}
            </p>
        </div>
    );
};

export default VoiceExamples;
