-- Migration to add lifecycle tracking columns to public.profiles
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'total_generations') THEN
        ALTER TABLE public.profiles ADD COLUMN total_generations integer DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'last_aha_moment_at') THEN
        ALTER TABLE public.profiles ADD COLUMN last_aha_moment_at timestamptz;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'marketing_opt_in') THEN
        ALTER TABLE public.profiles ADD COLUMN marketing_opt_in boolean DEFAULT true;
    END IF;
END $$;

COMMENT ON COLUMN public.profiles.total_generations IS 'Total number of posts generated by the user.';
COMMENT ON COLUMN public.profiles.last_aha_moment_at IS 'The timestamp when the user first experienced significant value (e.g., successful post generation).';
COMMENT ON COLUMN public.profiles.marketing_opt_in IS 'Whether the user has opted in to marketing communications.';
